/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : MIDI
 #	author : miyako
 #	2016/03/21
 #
 # --------------------------------------------------------------------------------*/



// --- MIDI
void MIDI_Play(sLONG_PTR *pResult, PackagePtr pParams);
void MIDI_ABORT(sLONG_PTR *pResult, PackagePtr pParams);
void MIDI_SUSPEND(sLONG_PTR *pResult, PackagePtr pParams);
void MIDI_RESUME(sLONG_PTR *pResult, PackagePtr pParams);
