/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-midi.h
 #	source generated by 4D Plugin Wizard
 #	Project : midi
 #	author : miyako
 #	2020/11/20
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MIDI_H
#define PLUGIN_MIDI_H

#include "4DPluginAPI.h"
#include "C_LONGINT.h"
#include "C_TEXT.h"
#include "ARRAY_TEXT.h"

#include <map>
#include <mutex>

#if VERSIONMAC
#import <Cocoa/Cocoa.h>
#endif

#pragma mark -

void MIDI_Play(PA_PluginParameters params);
void MIDI_ABORT(PA_PluginParameters params);
void MIDI_SUSPEND(PA_PluginParameters params);
void MIDI_RESUME(PA_PluginParameters params);
void MIDI_Is_running(PA_PluginParameters params);

#endif /* PLUGIN_MIDI_H */
